export const routes = {
  dashboard: "/dashboard",
  orders: "/orders",
  merchants: "/merchants",
  products: "/products",
  employers: "/employers",
  reports: "/reports",
  messages: "/messages",
  map: "/map",
  profile: "/profile",
  signin: "/signin",
  signup: "/signup",
  reset: "/reset",
  admin: "/admin",
  nowhere: "/",
};
